theme: jekyll-theme-cayman

title: "Vento Data Science Consulting (VDSC) LLC"
description: "Analyzing everything from business to physics, VDSC got you covered"

url: "https://cventophd.github.io"
baseurl: "/VDSC.io"

github:
  is_project_page: true
  repository_url: "https://github.com/cventophd/VDSC.io"
